// flow-typed signature: 89500e08bba93481dc8b93517a658672
// flow-typed version: <<STUB>>/array-flatten_v^2.1.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array-flatten'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'array-flatten' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'array-flatten/array-flatten' {
  declare module.exports: any;
}

// Filename aliases
declare module 'array-flatten/array-flatten.js' {
  declare module.exports: $Exports<'array-flatten/array-flatten'>;
}
