// flow-typed signature: 88674fc8a0c6fce9cd7b4fd4178b0dd1
// flow-typed version: <<STUB>>/binary-version-reader_v^0.5.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'binary-version-reader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'binary-version-reader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'binary-version-reader/bin/pmod' {
  declare module.exports: any;
}

declare module 'binary-version-reader/cli' {
  declare module.exports: any;
}

declare module 'binary-version-reader/lib/BufferStream' {
  declare module.exports: any;
}

declare module 'binary-version-reader/lib/FirmwareModule' {
  declare module.exports: any;
}

declare module 'binary-version-reader/lib/HalDependencyResolver' {
  declare module.exports: any;
}

declare module 'binary-version-reader/lib/HalDescribeParser' {
  declare module.exports: any;
}

declare module 'binary-version-reader/lib/HalModuleParser' {
  declare module.exports: any;
}

declare module 'binary-version-reader/lib/utilities' {
  declare module.exports: any;
}

declare module 'binary-version-reader/main' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/042_describe.json' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/describe_no_usermodule' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/describe_no_usermodule2' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/describe_one_systemmodule.json' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/describe.json' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/fixed_dependencies_describe.json' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/fixed_describe.json' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/multiple_dependencies.json' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/old_describe.json' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/safe_mode_1.json' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/safe_mode_2.json' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/safe_mode_3.json' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/three_system_modules_with_firmware_reset.json' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/describes/three_system_modules.json' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/lib/FirmwareModule.spec' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/lib/HalDependencyResolver.spec' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/lib/HalDescribeParser.spec' {
  declare module.exports: any;
}

declare module 'binary-version-reader/specs/lib/HalModuleParser.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'binary-version-reader/bin/pmod.js' {
  declare module.exports: $Exports<'binary-version-reader/bin/pmod'>;
}
declare module 'binary-version-reader/cli.js' {
  declare module.exports: $Exports<'binary-version-reader/cli'>;
}
declare module 'binary-version-reader/lib/BufferStream.js' {
  declare module.exports: $Exports<'binary-version-reader/lib/BufferStream'>;
}
declare module 'binary-version-reader/lib/FirmwareModule.js' {
  declare module.exports: $Exports<'binary-version-reader/lib/FirmwareModule'>;
}
declare module 'binary-version-reader/lib/HalDependencyResolver.js' {
  declare module.exports: $Exports<'binary-version-reader/lib/HalDependencyResolver'>;
}
declare module 'binary-version-reader/lib/HalDescribeParser.js' {
  declare module.exports: $Exports<'binary-version-reader/lib/HalDescribeParser'>;
}
declare module 'binary-version-reader/lib/HalModuleParser.js' {
  declare module.exports: $Exports<'binary-version-reader/lib/HalModuleParser'>;
}
declare module 'binary-version-reader/lib/utilities.js' {
  declare module.exports: $Exports<'binary-version-reader/lib/utilities'>;
}
declare module 'binary-version-reader/main.js' {
  declare module.exports: $Exports<'binary-version-reader/main'>;
}
declare module 'binary-version-reader/specs/describes/042_describe.json.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/042_describe.json'>;
}
declare module 'binary-version-reader/specs/describes/describe_no_usermodule.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/describe_no_usermodule'>;
}
declare module 'binary-version-reader/specs/describes/describe_no_usermodule2.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/describe_no_usermodule2'>;
}
declare module 'binary-version-reader/specs/describes/describe_one_systemmodule.json.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/describe_one_systemmodule.json'>;
}
declare module 'binary-version-reader/specs/describes/describe.json.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/describe.json'>;
}
declare module 'binary-version-reader/specs/describes/fixed_dependencies_describe.json.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/fixed_dependencies_describe.json'>;
}
declare module 'binary-version-reader/specs/describes/fixed_describe.json.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/fixed_describe.json'>;
}
declare module 'binary-version-reader/specs/describes/multiple_dependencies.json.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/multiple_dependencies.json'>;
}
declare module 'binary-version-reader/specs/describes/old_describe.json.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/old_describe.json'>;
}
declare module 'binary-version-reader/specs/describes/safe_mode_1.json.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/safe_mode_1.json'>;
}
declare module 'binary-version-reader/specs/describes/safe_mode_2.json.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/safe_mode_2.json'>;
}
declare module 'binary-version-reader/specs/describes/safe_mode_3.json.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/safe_mode_3.json'>;
}
declare module 'binary-version-reader/specs/describes/three_system_modules_with_firmware_reset.json.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/three_system_modules_with_firmware_reset.json'>;
}
declare module 'binary-version-reader/specs/describes/three_system_modules.json.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/describes/three_system_modules.json'>;
}
declare module 'binary-version-reader/specs/lib/FirmwareModule.spec.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/lib/FirmwareModule.spec'>;
}
declare module 'binary-version-reader/specs/lib/HalDependencyResolver.spec.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/lib/HalDependencyResolver.spec'>;
}
declare module 'binary-version-reader/specs/lib/HalDescribeParser.spec.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/lib/HalDescribeParser.spec'>;
}
declare module 'binary-version-reader/specs/lib/HalModuleParser.spec.js' {
  declare module.exports: $Exports<'binary-version-reader/specs/lib/HalModuleParser.spec'>;
}
