// flow-typed signature: 84e2d4a1bbb5d047b30cb2448fc44e64
// flow-typed version: <<STUB>>/constitute_v^1.6.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'constitute'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'constitute' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'constitute/example/es6-cjs/a' {
  declare module.exports: any;
}

declare module 'constitute/example/es6-cjs/b' {
  declare module.exports: any;
}

declare module 'constitute/example/es6-cjs/c' {
  declare module.exports: any;
}

declare module 'constitute/example/es6-cjs/main' {
  declare module.exports: any;
}

declare module 'constitute/example/es6-modules/a' {
  declare module.exports: any;
}

declare module 'constitute/example/es6-modules/b' {
  declare module.exports: any;
}

declare module 'constitute/example/es6-modules/c' {
  declare module.exports: any;
}

declare module 'constitute/example/es6-modules/main' {
  declare module.exports: any;
}

declare module 'constitute/example/es7-decorators/a' {
  declare module.exports: any;
}

declare module 'constitute/example/es7-decorators/b' {
  declare module.exports: any;
}

declare module 'constitute/example/es7-decorators/c' {
  declare module.exports: any;
}

declare module 'constitute/example/es7-decorators/main' {
  declare module.exports: any;
}

declare module 'constitute/lib/constitutors/base' {
  declare module.exports: any;
}

declare module 'constitute/lib/constitutors/global' {
  declare module.exports: any;
}

declare module 'constitute/lib/constitutors/singleton' {
  declare module.exports: any;
}

declare module 'constitute/lib/constitutors/transient' {
  declare module.exports: any;
}

declare module 'constitute/lib/container' {
  declare module.exports: any;
}

declare module 'constitute/lib/decorators/dependencies' {
  declare module.exports: any;
}

declare module 'constitute/lib/factories/alias' {
  declare module.exports: any;
}

declare module 'constitute/lib/factories/base' {
  declare module.exports: any;
}

declare module 'constitute/lib/factories/class' {
  declare module.exports: any;
}

declare module 'constitute/lib/factories/clone' {
  declare module.exports: any;
}

declare module 'constitute/lib/factories/method' {
  declare module.exports: any;
}

declare module 'constitute/lib/factories/null' {
  declare module.exports: any;
}

declare module 'constitute/lib/factories/value' {
  declare module.exports: any;
}

declare module 'constitute/lib/resolvers/all' {
  declare module.exports: any;
}

declare module 'constitute/lib/resolvers/base' {
  declare module.exports: any;
}

declare module 'constitute/lib/resolvers/instance' {
  declare module.exports: any;
}

declare module 'constitute/lib/resolvers/lazy' {
  declare module.exports: any;
}

declare module 'constitute/lib/resolvers/optional' {
  declare module.exports: any;
}

declare module 'constitute/lib/util' {
  declare module.exports: any;
}

declare module 'constitute/test/baseSpec' {
  declare module.exports: any;
}

declare module 'constitute/test/constituteSpec' {
  declare module.exports: any;
}

declare module 'constitute/test/containerSpec' {
  declare module.exports: any;
}

declare module 'constitute/test/helpers/babel' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/01_minimal' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/02_transient' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/03_global' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/04_value' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/05_alias' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/06_clone' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/07_method' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/08_multiple' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/09_plugin' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/10_lazy' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/11_optional' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/12_circular' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/13_post' {
  declare module.exports: any;
}

declare module 'constitute/test/samples/14_debug' {
  declare module.exports: any;
}

declare module 'constitute/test/singletonSpec' {
  declare module.exports: any;
}

declare module 'constitute/test/utilSpec' {
  declare module.exports: any;
}

declare module 'constitute/wallaby' {
  declare module.exports: any;
}

// Filename aliases
declare module 'constitute/example/es6-cjs/a.js' {
  declare module.exports: $Exports<'constitute/example/es6-cjs/a'>;
}
declare module 'constitute/example/es6-cjs/b.js' {
  declare module.exports: $Exports<'constitute/example/es6-cjs/b'>;
}
declare module 'constitute/example/es6-cjs/c.js' {
  declare module.exports: $Exports<'constitute/example/es6-cjs/c'>;
}
declare module 'constitute/example/es6-cjs/main.js' {
  declare module.exports: $Exports<'constitute/example/es6-cjs/main'>;
}
declare module 'constitute/example/es6-modules/a.js' {
  declare module.exports: $Exports<'constitute/example/es6-modules/a'>;
}
declare module 'constitute/example/es6-modules/b.js' {
  declare module.exports: $Exports<'constitute/example/es6-modules/b'>;
}
declare module 'constitute/example/es6-modules/c.js' {
  declare module.exports: $Exports<'constitute/example/es6-modules/c'>;
}
declare module 'constitute/example/es6-modules/main.js' {
  declare module.exports: $Exports<'constitute/example/es6-modules/main'>;
}
declare module 'constitute/example/es7-decorators/a.js' {
  declare module.exports: $Exports<'constitute/example/es7-decorators/a'>;
}
declare module 'constitute/example/es7-decorators/b.js' {
  declare module.exports: $Exports<'constitute/example/es7-decorators/b'>;
}
declare module 'constitute/example/es7-decorators/c.js' {
  declare module.exports: $Exports<'constitute/example/es7-decorators/c'>;
}
declare module 'constitute/example/es7-decorators/main.js' {
  declare module.exports: $Exports<'constitute/example/es7-decorators/main'>;
}
declare module 'constitute/index' {
  declare module.exports: $Exports<'constitute'>;
}
declare module 'constitute/index.js' {
  declare module.exports: $Exports<'constitute'>;
}
declare module 'constitute/lib/constitutors/base.js' {
  declare module.exports: $Exports<'constitute/lib/constitutors/base'>;
}
declare module 'constitute/lib/constitutors/global.js' {
  declare module.exports: $Exports<'constitute/lib/constitutors/global'>;
}
declare module 'constitute/lib/constitutors/singleton.js' {
  declare module.exports: $Exports<'constitute/lib/constitutors/singleton'>;
}
declare module 'constitute/lib/constitutors/transient.js' {
  declare module.exports: $Exports<'constitute/lib/constitutors/transient'>;
}
declare module 'constitute/lib/container.js' {
  declare module.exports: $Exports<'constitute/lib/container'>;
}
declare module 'constitute/lib/decorators/dependencies.js' {
  declare module.exports: $Exports<'constitute/lib/decorators/dependencies'>;
}
declare module 'constitute/lib/factories/alias.js' {
  declare module.exports: $Exports<'constitute/lib/factories/alias'>;
}
declare module 'constitute/lib/factories/base.js' {
  declare module.exports: $Exports<'constitute/lib/factories/base'>;
}
declare module 'constitute/lib/factories/class.js' {
  declare module.exports: $Exports<'constitute/lib/factories/class'>;
}
declare module 'constitute/lib/factories/clone.js' {
  declare module.exports: $Exports<'constitute/lib/factories/clone'>;
}
declare module 'constitute/lib/factories/method.js' {
  declare module.exports: $Exports<'constitute/lib/factories/method'>;
}
declare module 'constitute/lib/factories/null.js' {
  declare module.exports: $Exports<'constitute/lib/factories/null'>;
}
declare module 'constitute/lib/factories/value.js' {
  declare module.exports: $Exports<'constitute/lib/factories/value'>;
}
declare module 'constitute/lib/resolvers/all.js' {
  declare module.exports: $Exports<'constitute/lib/resolvers/all'>;
}
declare module 'constitute/lib/resolvers/base.js' {
  declare module.exports: $Exports<'constitute/lib/resolvers/base'>;
}
declare module 'constitute/lib/resolvers/instance.js' {
  declare module.exports: $Exports<'constitute/lib/resolvers/instance'>;
}
declare module 'constitute/lib/resolvers/lazy.js' {
  declare module.exports: $Exports<'constitute/lib/resolvers/lazy'>;
}
declare module 'constitute/lib/resolvers/optional.js' {
  declare module.exports: $Exports<'constitute/lib/resolvers/optional'>;
}
declare module 'constitute/lib/util.js' {
  declare module.exports: $Exports<'constitute/lib/util'>;
}
declare module 'constitute/test/baseSpec.js' {
  declare module.exports: $Exports<'constitute/test/baseSpec'>;
}
declare module 'constitute/test/constituteSpec.js' {
  declare module.exports: $Exports<'constitute/test/constituteSpec'>;
}
declare module 'constitute/test/containerSpec.js' {
  declare module.exports: $Exports<'constitute/test/containerSpec'>;
}
declare module 'constitute/test/helpers/babel.js' {
  declare module.exports: $Exports<'constitute/test/helpers/babel'>;
}
declare module 'constitute/test/samples/01_minimal.js' {
  declare module.exports: $Exports<'constitute/test/samples/01_minimal'>;
}
declare module 'constitute/test/samples/02_transient.js' {
  declare module.exports: $Exports<'constitute/test/samples/02_transient'>;
}
declare module 'constitute/test/samples/03_global.js' {
  declare module.exports: $Exports<'constitute/test/samples/03_global'>;
}
declare module 'constitute/test/samples/04_value.js' {
  declare module.exports: $Exports<'constitute/test/samples/04_value'>;
}
declare module 'constitute/test/samples/05_alias.js' {
  declare module.exports: $Exports<'constitute/test/samples/05_alias'>;
}
declare module 'constitute/test/samples/06_clone.js' {
  declare module.exports: $Exports<'constitute/test/samples/06_clone'>;
}
declare module 'constitute/test/samples/07_method.js' {
  declare module.exports: $Exports<'constitute/test/samples/07_method'>;
}
declare module 'constitute/test/samples/08_multiple.js' {
  declare module.exports: $Exports<'constitute/test/samples/08_multiple'>;
}
declare module 'constitute/test/samples/09_plugin.js' {
  declare module.exports: $Exports<'constitute/test/samples/09_plugin'>;
}
declare module 'constitute/test/samples/10_lazy.js' {
  declare module.exports: $Exports<'constitute/test/samples/10_lazy'>;
}
declare module 'constitute/test/samples/11_optional.js' {
  declare module.exports: $Exports<'constitute/test/samples/11_optional'>;
}
declare module 'constitute/test/samples/12_circular.js' {
  declare module.exports: $Exports<'constitute/test/samples/12_circular'>;
}
declare module 'constitute/test/samples/13_post.js' {
  declare module.exports: $Exports<'constitute/test/samples/13_post'>;
}
declare module 'constitute/test/samples/14_debug.js' {
  declare module.exports: $Exports<'constitute/test/samples/14_debug'>;
}
declare module 'constitute/test/singletonSpec.js' {
  declare module.exports: $Exports<'constitute/test/singletonSpec'>;
}
declare module 'constitute/test/utilSpec.js' {
  declare module.exports: $Exports<'constitute/test/utilSpec'>;
}
declare module 'constitute/wallaby.js' {
  declare module.exports: $Exports<'constitute/wallaby'>;
}
