// flow-typed signature: 49257411657742d7109dd930bacbfb41
// flow-typed version: <<STUB>>/ec-key_vhttps://github.com/Brewskey/ec-key

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ec-key'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ec-key' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ec-key/gulpfile' {
  declare module.exports: any;
}

declare module 'ec-key/src/ec-key' {
  declare module.exports: any;
}

declare module 'ec-key/test/ec-key.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ec-key/gulpfile.js' {
  declare module.exports: $Exports<'ec-key/gulpfile'>;
}
declare module 'ec-key/src/ec-key.js' {
  declare module.exports: $Exports<'ec-key/src/ec-key'>;
}
declare module 'ec-key/test/ec-key.test.js' {
  declare module.exports: $Exports<'ec-key/test/ec-key.test'>;
}
