// flow-typed signature: 9c58530a48e155a5ed56d9f6a72f498a
// flow-typed version: <<STUB>>/express-oauth-server_v^2.0.0-b3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-oauth-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-oauth-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-oauth-server/examples/memory/model' {
  declare module.exports: any;
}

declare module 'express-oauth-server/examples/mongodb/model' {
  declare module.exports: any;
}

declare module 'express-oauth-server/examples/postgresql/index' {
  declare module.exports: any;
}

declare module 'express-oauth-server/examples/postgresql/model' {
  declare module.exports: any;
}

declare module 'express-oauth-server/examples/redis/index' {
  declare module.exports: any;
}

declare module 'express-oauth-server/examples/redis/model' {
  declare module.exports: any;
}

declare module 'express-oauth-server/examples/redis/testData' {
  declare module.exports: any;
}

declare module 'express-oauth-server/test/integration/index_test' {
  declare module.exports: any;
}

declare module 'express-oauth-server/test/unit/index_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-oauth-server/examples/memory/model.js' {
  declare module.exports: $Exports<'express-oauth-server/examples/memory/model'>;
}
declare module 'express-oauth-server/examples/mongodb/model.js' {
  declare module.exports: $Exports<'express-oauth-server/examples/mongodb/model'>;
}
declare module 'express-oauth-server/examples/postgresql/index.js' {
  declare module.exports: $Exports<'express-oauth-server/examples/postgresql/index'>;
}
declare module 'express-oauth-server/examples/postgresql/model.js' {
  declare module.exports: $Exports<'express-oauth-server/examples/postgresql/model'>;
}
declare module 'express-oauth-server/examples/redis/index.js' {
  declare module.exports: $Exports<'express-oauth-server/examples/redis/index'>;
}
declare module 'express-oauth-server/examples/redis/model.js' {
  declare module.exports: $Exports<'express-oauth-server/examples/redis/model'>;
}
declare module 'express-oauth-server/examples/redis/testData.js' {
  declare module.exports: $Exports<'express-oauth-server/examples/redis/testData'>;
}
declare module 'express-oauth-server/index' {
  declare module.exports: $Exports<'express-oauth-server'>;
}
declare module 'express-oauth-server/index.js' {
  declare module.exports: $Exports<'express-oauth-server'>;
}
declare module 'express-oauth-server/test/integration/index_test.js' {
  declare module.exports: $Exports<'express-oauth-server/test/integration/index_test'>;
}
declare module 'express-oauth-server/test/unit/index_test.js' {
  declare module.exports: $Exports<'express-oauth-server/test/unit/index_test'>;
}
