// flow-typed signature: f12b5db19d4df60ad19b763bd0e0912f
// flow-typed version: <<STUB>>/hogan.js_v^3.0.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hogan.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hogan.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hogan.js/build/gh-pages/1.0.0/hogan' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/1.0.0/hogan.min' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.0/hogan' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.0/hogan.min' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.3/hogan' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.3/hogan.min' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.common' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.min.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.min.common' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.min' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.min.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.4/template-1.0.4' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.4/template-1.0.4.min' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.common' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.min.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.min.common' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.min' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.min.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.5/template-1.0.5' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/1.0.5/template-1.0.5.min' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.common' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.min.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.min.common' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.min' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.min.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/2.0.0/template-2.0.0' {
  declare module.exports: any;
}

declare module 'hogan.js/build/gh-pages/builds/2.0.0/template-2.0.0.min' {
  declare module.exports: any;
}

declare module 'hogan.js/dist/hogan-3.0.2.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/dist/hogan-3.0.2.common' {
  declare module.exports: any;
}

declare module 'hogan.js/dist/hogan-3.0.2' {
  declare module.exports: any;
}

declare module 'hogan.js/dist/hogan-3.0.2.min.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/dist/hogan-3.0.2.min.common' {
  declare module.exports: any;
}

declare module 'hogan.js/dist/hogan-3.0.2.min' {
  declare module.exports: any;
}

declare module 'hogan.js/dist/hogan-3.0.2.min.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/dist/hogan-3.0.2.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/dist/template-3.0.2' {
  declare module.exports: any;
}

declare module 'hogan.js/dist/template-3.0.2.min' {
  declare module.exports: any;
}

declare module 'hogan.js/inheritance' {
  declare module.exports: any;
}

declare module 'hogan.js/lib/compiler' {
  declare module.exports: any;
}

declare module 'hogan.js/lib/hogan' {
  declare module.exports: any;
}

declare module 'hogan.js/lib/template' {
  declare module.exports: any;
}

declare module 'hogan.js/test' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.0/hogan' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.0/hogan.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.3/hogan' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.3/hogan.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.min.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.min.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.min.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.4/template-1.0.4' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.4/template-1.0.4.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.min.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.min.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.min.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.5/template-1.0.5' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/1.0.5/template-1.0.5.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.min.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.min.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.min.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/2.0.0/template-2.0.0' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/2.0.0/template-2.0.0.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.min.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.min.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.min.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.min.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.min.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.min.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.min.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.min.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.min.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.min.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.min.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.min.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.min.amd' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.min.common' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.min' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.min.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.mustache' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.2/template-3.0.2' {
  declare module.exports: any;
}

declare module 'hogan.js/web/builds/3.0.2/template-3.0.2.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hogan.js/build/gh-pages/1.0.0/hogan.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/1.0.0/hogan'>;
}
declare module 'hogan.js/build/gh-pages/1.0.0/hogan.min.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/1.0.0/hogan.min'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.0/hogan.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.0/hogan'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.0/hogan.min.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.0/hogan.min'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.3/hogan.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.3/hogan'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.3/hogan.min.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.3/hogan.min'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.amd.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.amd'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.common.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.common'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.min.amd.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.min.amd'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.min.common.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.min.common'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.min.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.min'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.min.mustache.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.min.mustache'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.mustache.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.4/hogan-1.0.4.mustache'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.4/template-1.0.4.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.4/template-1.0.4'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.4/template-1.0.4.min.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.4/template-1.0.4.min'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.amd.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.amd'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.common.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.common'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.min.amd.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.min.amd'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.min.common.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.min.common'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.min.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.min'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.min.mustache.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.min.mustache'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.mustache.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.5/hogan-1.0.5.mustache'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.5/template-1.0.5.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.5/template-1.0.5'>;
}
declare module 'hogan.js/build/gh-pages/builds/1.0.5/template-1.0.5.min.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/1.0.5/template-1.0.5.min'>;
}
declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.amd.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.amd'>;
}
declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.common.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.common'>;
}
declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0'>;
}
declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.min.amd.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.min.amd'>;
}
declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.min.common.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.min.common'>;
}
declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.min.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.min'>;
}
declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.min.mustache.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.min.mustache'>;
}
declare module 'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.mustache.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/2.0.0/hogan-2.0.0.mustache'>;
}
declare module 'hogan.js/build/gh-pages/builds/2.0.0/template-2.0.0.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/2.0.0/template-2.0.0'>;
}
declare module 'hogan.js/build/gh-pages/builds/2.0.0/template-2.0.0.min.js' {
  declare module.exports: $Exports<'hogan.js/build/gh-pages/builds/2.0.0/template-2.0.0.min'>;
}
declare module 'hogan.js/dist/hogan-3.0.2.amd.js' {
  declare module.exports: $Exports<'hogan.js/dist/hogan-3.0.2.amd'>;
}
declare module 'hogan.js/dist/hogan-3.0.2.common.js' {
  declare module.exports: $Exports<'hogan.js/dist/hogan-3.0.2.common'>;
}
declare module 'hogan.js/dist/hogan-3.0.2.js' {
  declare module.exports: $Exports<'hogan.js/dist/hogan-3.0.2'>;
}
declare module 'hogan.js/dist/hogan-3.0.2.min.amd.js' {
  declare module.exports: $Exports<'hogan.js/dist/hogan-3.0.2.min.amd'>;
}
declare module 'hogan.js/dist/hogan-3.0.2.min.common.js' {
  declare module.exports: $Exports<'hogan.js/dist/hogan-3.0.2.min.common'>;
}
declare module 'hogan.js/dist/hogan-3.0.2.min.js' {
  declare module.exports: $Exports<'hogan.js/dist/hogan-3.0.2.min'>;
}
declare module 'hogan.js/dist/hogan-3.0.2.min.mustache.js' {
  declare module.exports: $Exports<'hogan.js/dist/hogan-3.0.2.min.mustache'>;
}
declare module 'hogan.js/dist/hogan-3.0.2.mustache.js' {
  declare module.exports: $Exports<'hogan.js/dist/hogan-3.0.2.mustache'>;
}
declare module 'hogan.js/dist/template-3.0.2.js' {
  declare module.exports: $Exports<'hogan.js/dist/template-3.0.2'>;
}
declare module 'hogan.js/dist/template-3.0.2.min.js' {
  declare module.exports: $Exports<'hogan.js/dist/template-3.0.2.min'>;
}
declare module 'hogan.js/inheritance.js' {
  declare module.exports: $Exports<'hogan.js/inheritance'>;
}
declare module 'hogan.js/lib/compiler.js' {
  declare module.exports: $Exports<'hogan.js/lib/compiler'>;
}
declare module 'hogan.js/lib/hogan.js' {
  declare module.exports: $Exports<'hogan.js/lib/hogan'>;
}
declare module 'hogan.js/lib/template.js' {
  declare module.exports: $Exports<'hogan.js/lib/template'>;
}
declare module 'hogan.js/test.js' {
  declare module.exports: $Exports<'hogan.js/test'>;
}
declare module 'hogan.js/web/builds/1.0.0/hogan.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.0/hogan'>;
}
declare module 'hogan.js/web/builds/1.0.0/hogan.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.0/hogan.min'>;
}
declare module 'hogan.js/web/builds/1.0.3/hogan.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.3/hogan'>;
}
declare module 'hogan.js/web/builds/1.0.3/hogan.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.3/hogan.min'>;
}
declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.4/hogan-1.0.4.amd'>;
}
declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.4/hogan-1.0.4.common'>;
}
declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.4/hogan-1.0.4'>;
}
declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.min.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.4/hogan-1.0.4.min.amd'>;
}
declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.min.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.4/hogan-1.0.4.min.common'>;
}
declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.4/hogan-1.0.4.min'>;
}
declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.min.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.4/hogan-1.0.4.min.mustache'>;
}
declare module 'hogan.js/web/builds/1.0.4/hogan-1.0.4.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.4/hogan-1.0.4.mustache'>;
}
declare module 'hogan.js/web/builds/1.0.4/template-1.0.4.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.4/template-1.0.4'>;
}
declare module 'hogan.js/web/builds/1.0.4/template-1.0.4.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.4/template-1.0.4.min'>;
}
declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.5/hogan-1.0.5.amd'>;
}
declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.5/hogan-1.0.5.common'>;
}
declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.5/hogan-1.0.5'>;
}
declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.min.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.5/hogan-1.0.5.min.amd'>;
}
declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.min.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.5/hogan-1.0.5.min.common'>;
}
declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.5/hogan-1.0.5.min'>;
}
declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.min.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.5/hogan-1.0.5.min.mustache'>;
}
declare module 'hogan.js/web/builds/1.0.5/hogan-1.0.5.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.5/hogan-1.0.5.mustache'>;
}
declare module 'hogan.js/web/builds/1.0.5/template-1.0.5.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.5/template-1.0.5'>;
}
declare module 'hogan.js/web/builds/1.0.5/template-1.0.5.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/1.0.5/template-1.0.5.min'>;
}
declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/2.0.0/hogan-2.0.0.amd'>;
}
declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/2.0.0/hogan-2.0.0.common'>;
}
declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/2.0.0/hogan-2.0.0'>;
}
declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.min.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/2.0.0/hogan-2.0.0.min.amd'>;
}
declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.min.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/2.0.0/hogan-2.0.0.min.common'>;
}
declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/2.0.0/hogan-2.0.0.min'>;
}
declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.min.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/2.0.0/hogan-2.0.0.min.mustache'>;
}
declare module 'hogan.js/web/builds/2.0.0/hogan-2.0.0.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/2.0.0/hogan-2.0.0.mustache'>;
}
declare module 'hogan.js/web/builds/2.0.0/template-2.0.0.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/2.0.0/template-2.0.0'>;
}
declare module 'hogan.js/web/builds/2.0.0/template-2.0.0.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/2.0.0/template-2.0.0.min'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan-3.0.0.amd'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan-3.0.0.common'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan-3.0.0'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.min.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan-3.0.0.min.amd'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.min.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan-3.0.0.min.common'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan-3.0.0.min'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.min.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan-3.0.0.min.mustache'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan-3.0.0.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan-3.0.0.mustache'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.amd'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.common'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan.template-3.0.0'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.min.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.min.amd'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.min.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.min.common'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.min'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.min.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.min.mustache'>;
}
declare module 'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.0/hogan.template-3.0.0.mustache'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan-3.0.1.amd'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan-3.0.1.common'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan-3.0.1'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.min.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan-3.0.1.min.amd'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.min.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan-3.0.1.min.common'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan-3.0.1.min'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.min.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan-3.0.1.min.mustache'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan-3.0.1.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan-3.0.1.mustache'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.amd'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.common'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan.template-3.0.1'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.min.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.min.amd'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.min.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.min.common'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.min'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.min.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.min.mustache'>;
}
declare module 'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.1/hogan.template-3.0.1.mustache'>;
}
declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.2/hogan-3.0.2.amd'>;
}
declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.2/hogan-3.0.2.common'>;
}
declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.2/hogan-3.0.2'>;
}
declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.min.amd.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.2/hogan-3.0.2.min.amd'>;
}
declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.min.common.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.2/hogan-3.0.2.min.common'>;
}
declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.2/hogan-3.0.2.min'>;
}
declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.min.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.2/hogan-3.0.2.min.mustache'>;
}
declare module 'hogan.js/web/builds/3.0.2/hogan-3.0.2.mustache.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.2/hogan-3.0.2.mustache'>;
}
declare module 'hogan.js/web/builds/3.0.2/template-3.0.2.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.2/template-3.0.2'>;
}
declare module 'hogan.js/web/builds/3.0.2/template-3.0.2.min.js' {
  declare module.exports: $Exports<'hogan.js/web/builds/3.0.2/template-3.0.2.min'>;
}
