// flow-typed signature: 55c6e18dcec1d5d1ab36d4464badec18
// flow-typed version: <<STUB>>/nedb-core_v^3.0.6

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nedb-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nedb-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nedb-core/lib/cursor' {
  declare module.exports: any;
}

declare module 'nedb-core/lib/custom-utils' {
  declare module.exports: any;
}

declare module 'nedb-core/lib/datastore' {
  declare module.exports: any;
}

declare module 'nedb-core/lib/executor' {
  declare module.exports: any;
}

declare module 'nedb-core/lib/indexes' {
  declare module.exports: any;
}

declare module 'nedb-core/lib/model' {
  declare module.exports: any;
}

declare module 'nedb-core/lib/persistence' {
  declare module.exports: any;
}

declare module 'nedb-core/lib/storage' {
  declare module.exports: any;
}

declare module 'nedb-core/lib/tree/avl' {
  declare module.exports: any;
}

declare module 'nedb-core/lib/tree/bst' {
  declare module.exports: any;
}

declare module 'nedb-core/lib/tree/custom-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nedb-core/index' {
  declare module.exports: $Exports<'nedb-core'>;
}
declare module 'nedb-core/index.js' {
  declare module.exports: $Exports<'nedb-core'>;
}
declare module 'nedb-core/lib/cursor.js' {
  declare module.exports: $Exports<'nedb-core/lib/cursor'>;
}
declare module 'nedb-core/lib/custom-utils.js' {
  declare module.exports: $Exports<'nedb-core/lib/custom-utils'>;
}
declare module 'nedb-core/lib/datastore.js' {
  declare module.exports: $Exports<'nedb-core/lib/datastore'>;
}
declare module 'nedb-core/lib/executor.js' {
  declare module.exports: $Exports<'nedb-core/lib/executor'>;
}
declare module 'nedb-core/lib/indexes.js' {
  declare module.exports: $Exports<'nedb-core/lib/indexes'>;
}
declare module 'nedb-core/lib/model.js' {
  declare module.exports: $Exports<'nedb-core/lib/model'>;
}
declare module 'nedb-core/lib/persistence.js' {
  declare module.exports: $Exports<'nedb-core/lib/persistence'>;
}
declare module 'nedb-core/lib/storage.js' {
  declare module.exports: $Exports<'nedb-core/lib/storage'>;
}
declare module 'nedb-core/lib/tree/avl.js' {
  declare module.exports: $Exports<'nedb-core/lib/tree/avl'>;
}
declare module 'nedb-core/lib/tree/bst.js' {
  declare module.exports: $Exports<'nedb-core/lib/tree/bst'>;
}
declare module 'nedb-core/lib/tree/custom-utils.js' {
  declare module.exports: $Exports<'nedb-core/lib/tree/custom-utils'>;
}
