// flow-typed signature: 3a098f2d64f849e7bbfe65c100856ae6
// flow-typed version: <<STUB>>/spark-protocol_vhttps://github.com/Brewskey/spark-protocol.git#dev

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spark-protocol'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spark-protocol' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spark-protocol/dist/clients/Device' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/decorators/memoizeGet' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/decorators/memoizeSet' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/decorators/types' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/defaultBindings' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/index' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/BufferStream' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/ChunkingStream' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/ClaimCodeManager' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/CoapMessage' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/CoapMessages' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/CryptoManager' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/CryptoStream' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/DeviceKey' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/EventProvider' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/EventPublisher' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/FileTransferStore' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/FirmwareManager' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/Flasher' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/Handshake' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/logger' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/MessageSpecifications' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/ProtocolErrors' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/SparkServerEvents' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/lib/SparkServerRequestEvents' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/repository/DeviceAttributeFileRepository' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/repository/DeviceKeyFileRepository' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/repository/FileManager' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/repository/JSONFileManager' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/repository/MockProductDeviceRepository' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/repository/MockProductFirmwareRepository' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/repository/ServerKeyFileRepository' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/scripts/update-firmware-binaries' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/server/DeviceServer' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/settings' {
  declare module.exports: any;
}

declare module 'spark-protocol/dist/types' {
  declare module.exports: any;
}

declare module 'spark-protocol/flow-typed/CoapPacket.flow' {
  declare module.exports: any;
}

declare module 'spark-protocol/flow-typed/npm/express_v4.x.x' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/clients/Device' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/decorators/memoizeGet' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/decorators/memoizeSet' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/decorators/types' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/defaultBindings' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/index' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/BufferStream' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/ChunkingStream' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/ClaimCodeManager' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/CoapMessage' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/CoapMessages' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/CryptoManager' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/CryptoStream' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/DeviceKey' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/EventProvider' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/EventPublisher' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/FileTransferStore' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/FirmwareManager' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/Flasher' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/Handshake' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/logger' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/MessageSpecifications' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/ProtocolErrors' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/lib/SparkServerEvents' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/repository/DeviceAttributeFileRepository' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/repository/DeviceKeyFileRepository' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/repository/FileManager' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/repository/JSONFileManager' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/repository/MockProductDeviceRepository' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/repository/MockProductFirmwareRepository' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/repository/ServerKeyFileRepository' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/scripts/update-firmware-binaries' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/server/DeviceServer' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/settings' {
  declare module.exports: any;
}

declare module 'spark-protocol/src/types' {
  declare module.exports: any;
}

declare module 'spark-protocol/test/EventPublisher.test' {
  declare module.exports: any;
}

declare module 'spark-protocol/test/setup/TestData' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spark-protocol/dist/clients/Device.js' {
  declare module.exports: $Exports<'spark-protocol/dist/clients/Device'>;
}
declare module 'spark-protocol/dist/decorators/memoizeGet.js' {
  declare module.exports: $Exports<'spark-protocol/dist/decorators/memoizeGet'>;
}
declare module 'spark-protocol/dist/decorators/memoizeSet.js' {
  declare module.exports: $Exports<'spark-protocol/dist/decorators/memoizeSet'>;
}
declare module 'spark-protocol/dist/decorators/types.js' {
  declare module.exports: $Exports<'spark-protocol/dist/decorators/types'>;
}
declare module 'spark-protocol/dist/defaultBindings.js' {
  declare module.exports: $Exports<'spark-protocol/dist/defaultBindings'>;
}
declare module 'spark-protocol/dist/index.js' {
  declare module.exports: $Exports<'spark-protocol/dist/index'>;
}
declare module 'spark-protocol/dist/lib/BufferStream.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/BufferStream'>;
}
declare module 'spark-protocol/dist/lib/ChunkingStream.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/ChunkingStream'>;
}
declare module 'spark-protocol/dist/lib/ClaimCodeManager.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/ClaimCodeManager'>;
}
declare module 'spark-protocol/dist/lib/CoapMessage.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/CoapMessage'>;
}
declare module 'spark-protocol/dist/lib/CoapMessages.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/CoapMessages'>;
}
declare module 'spark-protocol/dist/lib/CryptoManager.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/CryptoManager'>;
}
declare module 'spark-protocol/dist/lib/CryptoStream.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/CryptoStream'>;
}
declare module 'spark-protocol/dist/lib/DeviceKey.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/DeviceKey'>;
}
declare module 'spark-protocol/dist/lib/EventProvider.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/EventProvider'>;
}
declare module 'spark-protocol/dist/lib/EventPublisher.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/EventPublisher'>;
}
declare module 'spark-protocol/dist/lib/FileTransferStore.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/FileTransferStore'>;
}
declare module 'spark-protocol/dist/lib/FirmwareManager.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/FirmwareManager'>;
}
declare module 'spark-protocol/dist/lib/Flasher.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/Flasher'>;
}
declare module 'spark-protocol/dist/lib/Handshake.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/Handshake'>;
}
declare module 'spark-protocol/dist/lib/logger.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/logger'>;
}
declare module 'spark-protocol/dist/lib/MessageSpecifications.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/MessageSpecifications'>;
}
declare module 'spark-protocol/dist/lib/ProtocolErrors.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/ProtocolErrors'>;
}
declare module 'spark-protocol/dist/lib/SparkServerEvents.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/SparkServerEvents'>;
}
declare module 'spark-protocol/dist/lib/SparkServerRequestEvents.js' {
  declare module.exports: $Exports<'spark-protocol/dist/lib/SparkServerRequestEvents'>;
}
declare module 'spark-protocol/dist/repository/DeviceAttributeFileRepository.js' {
  declare module.exports: $Exports<'spark-protocol/dist/repository/DeviceAttributeFileRepository'>;
}
declare module 'spark-protocol/dist/repository/DeviceKeyFileRepository.js' {
  declare module.exports: $Exports<'spark-protocol/dist/repository/DeviceKeyFileRepository'>;
}
declare module 'spark-protocol/dist/repository/FileManager.js' {
  declare module.exports: $Exports<'spark-protocol/dist/repository/FileManager'>;
}
declare module 'spark-protocol/dist/repository/JSONFileManager.js' {
  declare module.exports: $Exports<'spark-protocol/dist/repository/JSONFileManager'>;
}
declare module 'spark-protocol/dist/repository/MockProductDeviceRepository.js' {
  declare module.exports: $Exports<'spark-protocol/dist/repository/MockProductDeviceRepository'>;
}
declare module 'spark-protocol/dist/repository/MockProductFirmwareRepository.js' {
  declare module.exports: $Exports<'spark-protocol/dist/repository/MockProductFirmwareRepository'>;
}
declare module 'spark-protocol/dist/repository/ServerKeyFileRepository.js' {
  declare module.exports: $Exports<'spark-protocol/dist/repository/ServerKeyFileRepository'>;
}
declare module 'spark-protocol/dist/scripts/update-firmware-binaries.js' {
  declare module.exports: $Exports<'spark-protocol/dist/scripts/update-firmware-binaries'>;
}
declare module 'spark-protocol/dist/server/DeviceServer.js' {
  declare module.exports: $Exports<'spark-protocol/dist/server/DeviceServer'>;
}
declare module 'spark-protocol/dist/settings.js' {
  declare module.exports: $Exports<'spark-protocol/dist/settings'>;
}
declare module 'spark-protocol/dist/types.js' {
  declare module.exports: $Exports<'spark-protocol/dist/types'>;
}
declare module 'spark-protocol/flow-typed/CoapPacket.flow.js' {
  declare module.exports: $Exports<'spark-protocol/flow-typed/CoapPacket.flow'>;
}
declare module 'spark-protocol/flow-typed/npm/express_v4.x.x.js' {
  declare module.exports: $Exports<'spark-protocol/flow-typed/npm/express_v4.x.x'>;
}
declare module 'spark-protocol/src/clients/Device.js' {
  declare module.exports: $Exports<'spark-protocol/src/clients/Device'>;
}
declare module 'spark-protocol/src/decorators/memoizeGet.js' {
  declare module.exports: $Exports<'spark-protocol/src/decorators/memoizeGet'>;
}
declare module 'spark-protocol/src/decorators/memoizeSet.js' {
  declare module.exports: $Exports<'spark-protocol/src/decorators/memoizeSet'>;
}
declare module 'spark-protocol/src/decorators/types.js' {
  declare module.exports: $Exports<'spark-protocol/src/decorators/types'>;
}
declare module 'spark-protocol/src/defaultBindings.js' {
  declare module.exports: $Exports<'spark-protocol/src/defaultBindings'>;
}
declare module 'spark-protocol/src/index.js' {
  declare module.exports: $Exports<'spark-protocol/src/index'>;
}
declare module 'spark-protocol/src/lib/BufferStream.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/BufferStream'>;
}
declare module 'spark-protocol/src/lib/ChunkingStream.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/ChunkingStream'>;
}
declare module 'spark-protocol/src/lib/ClaimCodeManager.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/ClaimCodeManager'>;
}
declare module 'spark-protocol/src/lib/CoapMessage.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/CoapMessage'>;
}
declare module 'spark-protocol/src/lib/CoapMessages.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/CoapMessages'>;
}
declare module 'spark-protocol/src/lib/CryptoManager.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/CryptoManager'>;
}
declare module 'spark-protocol/src/lib/CryptoStream.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/CryptoStream'>;
}
declare module 'spark-protocol/src/lib/DeviceKey.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/DeviceKey'>;
}
declare module 'spark-protocol/src/lib/EventProvider.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/EventProvider'>;
}
declare module 'spark-protocol/src/lib/EventPublisher.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/EventPublisher'>;
}
declare module 'spark-protocol/src/lib/FileTransferStore.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/FileTransferStore'>;
}
declare module 'spark-protocol/src/lib/FirmwareManager.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/FirmwareManager'>;
}
declare module 'spark-protocol/src/lib/Flasher.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/Flasher'>;
}
declare module 'spark-protocol/src/lib/Handshake.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/Handshake'>;
}
declare module 'spark-protocol/src/lib/logger.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/logger'>;
}
declare module 'spark-protocol/src/lib/MessageSpecifications.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/MessageSpecifications'>;
}
declare module 'spark-protocol/src/lib/ProtocolErrors.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/ProtocolErrors'>;
}
declare module 'spark-protocol/src/lib/SparkServerEvents.js' {
  declare module.exports: $Exports<'spark-protocol/src/lib/SparkServerEvents'>;
}
declare module 'spark-protocol/src/repository/DeviceAttributeFileRepository.js' {
  declare module.exports: $Exports<'spark-protocol/src/repository/DeviceAttributeFileRepository'>;
}
declare module 'spark-protocol/src/repository/DeviceKeyFileRepository.js' {
  declare module.exports: $Exports<'spark-protocol/src/repository/DeviceKeyFileRepository'>;
}
declare module 'spark-protocol/src/repository/FileManager.js' {
  declare module.exports: $Exports<'spark-protocol/src/repository/FileManager'>;
}
declare module 'spark-protocol/src/repository/JSONFileManager.js' {
  declare module.exports: $Exports<'spark-protocol/src/repository/JSONFileManager'>;
}
declare module 'spark-protocol/src/repository/MockProductDeviceRepository.js' {
  declare module.exports: $Exports<'spark-protocol/src/repository/MockProductDeviceRepository'>;
}
declare module 'spark-protocol/src/repository/MockProductFirmwareRepository.js' {
  declare module.exports: $Exports<'spark-protocol/src/repository/MockProductFirmwareRepository'>;
}
declare module 'spark-protocol/src/repository/ServerKeyFileRepository.js' {
  declare module.exports: $Exports<'spark-protocol/src/repository/ServerKeyFileRepository'>;
}
declare module 'spark-protocol/src/scripts/update-firmware-binaries.js' {
  declare module.exports: $Exports<'spark-protocol/src/scripts/update-firmware-binaries'>;
}
declare module 'spark-protocol/src/server/DeviceServer.js' {
  declare module.exports: $Exports<'spark-protocol/src/server/DeviceServer'>;
}
declare module 'spark-protocol/src/settings.js' {
  declare module.exports: $Exports<'spark-protocol/src/settings'>;
}
declare module 'spark-protocol/src/types.js' {
  declare module.exports: $Exports<'spark-protocol/src/types'>;
}
declare module 'spark-protocol/test/EventPublisher.test.js' {
  declare module.exports: $Exports<'spark-protocol/test/EventPublisher.test'>;
}
declare module 'spark-protocol/test/setup/TestData.js' {
  declare module.exports: $Exports<'spark-protocol/test/setup/TestData'>;
}
