// flow-typed signature: 86715e2780ac39a496b6370c0eafc12d
// flow-typed version: <<STUB>>/uglifyjs_v^2.4.10

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglifyjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglifyjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'uglifyjs/index' {
  declare module.exports: $Exports<'uglifyjs'>;
}
declare module 'uglifyjs/index.js' {
  declare module.exports: $Exports<'uglifyjs'>;
}
